// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqfchqssbxniiojmnrdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxZmNocXNzYnhuaWlvam1ucmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDk3ODUsImV4cCI6MjA1OTA4NTc4NX0.RLajuaKr1Nf8_YeV0TvNo1JXST3X88qQE8Nr3p4TKiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);